### ISSUE TITLE
Please fix your bugs

### ISSUE THREAD

**Issue by hezt** [392781/FaceOff#9]
Your codes are full of bugs. Could you please fix them? I don't think your examples can run successfully.

**Comment by YujunXie** [comment]
I agree. @392781

**Comment by 392781** [comment]
I was trying to do a rewrite of the routine a few months ago to clean it up, so yes most of the stuff isn't working exactly right. 

That being said, I haven't had the time to complete the rewrites.  Also I have moved on from this mostly because the work is a few years old at this point (and likely behind current research).

I'll get to this eventually.  For now though the code is provided as-is.  I'll approve any PRs if there's interest or any quick fixes in the mean time.  

Sorry about this and thank you for reminding me.

**Comment by 392781** [comment]
@YujunXie @hezt The latest commit af96aa6 fixed all the issues.  Please look at `README.md` for installation and `example.py` for usage.  

I really apologize for the delay... The method should be working find now as I originally intended for it to work.

I believe this is the last time I'll be updating this repo since I'm long done with the project... But I do appreciate feedback!
